name: image_card
description: A Flutter package provides a image card customization.
version: 0.0.3
homepage: https://github.com/zeref278/image_card.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
