// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxonhqtYbqQLORbx_-c-n2bWN0e-4Km3g',
    appId: '1:906403289387:web:7a1f8902ee9c78fc5a8d6e',
    messagingSenderId: '906403289387',
    projectId: 'fir-cruddemo-2bf79',
    authDomain: 'fir-cruddemo-2bf79.firebaseapp.com',
    storageBucket: 'fir-cruddemo-2bf79.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_2yPvrfXjqqqVLLhnHqfysm5sGbep9p8',
    appId: '1:906403289387:android:9b3dd6336afe48295a8d6e',
    messagingSenderId: '906403289387',
    projectId: 'fir-cruddemo-2bf79',
    storageBucket: 'fir-cruddemo-2bf79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHLJZc90HbbSd-80yOjpBNKbkRCWrAkNc',
    appId: '1:906403289387:ios:f022041fb8f26dc15a8d6e',
    messagingSenderId: '906403289387',
    projectId: 'fir-cruddemo-2bf79',
    storageBucket: 'fir-cruddemo-2bf79.appspot.com',
    iosClientId: '906403289387-4rj835vien8hdk7mq3rkg5l46ud7gs5a.apps.googleusercontent.com',
    iosBundleId: 'com.team.elearny',
  );
}
