// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZxU81inDFaqGEbVzhnMisOK6FmP-xJzk',
    appId: '1:52081032273:web:8bfaf99062e445e62c4c70',
    messagingSenderId: '52081032273',
    projectId: 'elearning-9f77b',
    authDomain: 'elearning-9f77b.firebaseapp.com',
    storageBucket: 'elearning-9f77b.appspot.com',
    measurementId: 'G-1C74Y6ZCKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIqdDUEDpI2gyJdDiNFjcjYa3eVaFPOGE',
    appId: '1:52081032273:android:c695bd226f6e2e932c4c70',
    messagingSenderId: '52081032273',
    projectId: 'elearning-9f77b',
    storageBucket: 'elearning-9f77b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPyfCbUX5CJdvkjQv4e8j6jAM8gxZj4IQ',
    appId: '1:52081032273:ios:fde9d16004e2a47b2c4c70',
    messagingSenderId: '52081032273',
    projectId: 'elearning-9f77b',
    storageBucket: 'elearning-9f77b.appspot.com',
    iosClientId: '52081032273-j3hh37rvr4o06k95m27hg9ilih5se2mq.apps.googleusercontent.com',
    iosBundleId: 'com.example.elearningProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPyfCbUX5CJdvkjQv4e8j6jAM8gxZj4IQ',
    appId: '1:52081032273:ios:fde9d16004e2a47b2c4c70',
    messagingSenderId: '52081032273',
    projectId: 'elearning-9f77b',
    storageBucket: 'elearning-9f77b.appspot.com',
    iosClientId: '52081032273-j3hh37rvr4o06k95m27hg9ilih5se2mq.apps.googleusercontent.com',
    iosBundleId: 'com.example.elearningProvider',
  );
}
